### ISSUE TITLE
Eliminate deployment downtime

### ISSUE THREAD

**Issue by joshbwlng** [product-os/jellyfish#5868]
## Goals
1. Determine how much downtime we encounter on average for each deployment.
2. Determine why this downtime occurs in the first place.

### Questions
- Why would downtime occur even though we're using Kubernetes to gracefully handle deployments?
  - Could it be due to backend bootstrapping taking time when Kubernetes things the pods are "ready"?

### Findings
- Downtime is recorded in our [statuspage](https://productos.statuspage.io/), using NodePing.
- We currently have no `readiness` and `liveness` checks are defined for action servers or tick server.

## ToDo
- [ ] Determine if session IDs etc could be lost from frontend on certain deployments.
- [ ] Check if `/readiness` in API is waiting for backend bootstrap to be complete.
- [ ] Add `readiness` and `liveness` checks for Kubernetes in action server, tick, and their Kubernetes configs.
  - We should consider merging the API and action servers together to avoid code duplication
